from __future__ import annotations

from pathlib import Path

from rich.console import Console

from lce.generators.agent_context_generator import AGENT_RULES
from lce.utils.file_utils import ensure_dir, write_text

console = Console()

DEFAULT_CONFIG = """version: 1
context_dir: .ai-context
default_output: .ai-context
scan:
  max_file_size_kb: 500
task:
  max_primary_files: 5
  max_secondary_files: 8
  max_context_files: 10
  max_avoid_files: 20
"""

CONTEXT_README = """# .ai-context

This folder is generated by Local Context Engine.

- `agent-context.md` gives AI coding agents a repository overview.
- `file-index.json` lists indexed files and lightweight metadata.
- `repo-map.json` summarizes repository structure.
- `tasks/` contains task-specific context packs.
"""


def init() -> None:
    """Initialize .ai-context in the current repository."""
    context_dir = Path(".ai-context")
    ensure_dir(context_dir)
    write_text(context_dir / "config.yml", DEFAULT_CONFIG)
    write_text(context_dir / "agent-rules.md", AGENT_RULES)
    write_text(context_dir / "README.md", CONTEXT_README)
    console.print("[green]Initialized .ai-context/[/green]")
